name: CI

on:
    push:
        branches:
            - 'feat/**'
        paths-ignore:
            - 'infra/**'
            - 'script/**'

env:
    IMAGE: ${{ vars.NCR_HOST }}/swns
    IMAGE_TAG: ${{ vars.NCR_HOST }}/swns:latest
    CONTAINER_NAME: swns-dj

jobs:
    lint:
        name: Check lint (black)
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'

            - name: Install black
              run: pip install black
            
            - name: check black
              run: black --check .
    
    build:
        needs: lint
        name: build image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: test
              run: |
                docker compose -f docker/docker-compose_test.yml up -d --build
                docker compose -f docker/docker-compose_test.yml exec swns python manage.py test
              env:
                NCP_ACCESS_KEY: ${{ secrets.NCP_ACCESS_KEY }}
                NCP_SECRET_KEY: ${{ secrets.NCP_SECRET_KEY }}
                NCP_S3_ENDPOINT_URL: ${{ vars.NCP_S3_ENDPOINT_URL }}
                NCP_S3_REGION_NAME: ${{ vars.NCP_S3_REGION_NAME }}
                NCP_S3_BUCKET_NAME: ${{ vars.NCP_S3_BUCKET_NAME }}
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_REGION: ${{ vars.AWS_REGION }}
                AWS_STORAGE_BUCKET_NAME: ${{ vars.AWS_STORAGE_BUCKET_NAME }}
            
            - name: Login to NCR
              uses: docker/login-action@v2
              with:
                registry: ${{ vars.NCR_HOST }}
                username: ${{ secrets.NCP_ACCESS_KEY }}
                password: ${{ secrets.NCP_SECRET_KEY }}
            
            - name: Get current timestamp
              id: image-tag
              run: echo "TIMESTAMP=$(date "+%s")" >> "$GITHUB_OUTPUT"

            - name: Build and Push
              uses: docker/build-push-action@v4
              with:
                context: .
                tags: ${{ env.IMAGE_TAG }}, ${{ env.IMAGE }}:${{ steps.image-tag.outputs.TIMESTAMP }}
                file: ./docker/Dockerfile_dj
                push: true

            - name: post test
              if: ${{ always() }}
              run: |
                docker compose -f docker/docker-compose_test.yml down
